# pywb config file
# ========================================
#
enable_memento: true
enable_auto_colls: true

recorder:
  filename_template: my-warc-{timestamp}-{hostname}-{random}.warc.gz
  source_coll: ia
  rollover_idle_secs: 10
#  rollover_size: 0

autoindex: 5
#recorder: live
collections:
  #  all: $all
  perma: memento+http://perma-archives.org/warc/
  ia: memento+https://web.archive.org/web/

archive_paths: archive
index_paths: indexes

collections_root: collections

# Settings for each collection
use_js_obj_proxy: true

# Replay content in an iframe
framed_replay: false

#static_url_path: dashboard/static
static_path: dashboard/static

static_dir: dashboard/static

templates_dir: dashboard/templates
banner_html: dashboard/templates/banner.html
head_insert_html: dashboard/templates/head_insert.html
frame_insert_html: dashboard/templates/frame_insert.html

# Enable simple http proxy mode
#enable_http_proxy: true